### PR TITLE
integrated saber

### PR DESCRIPTION
**Pull request by UbermenschSYM**
Integrated saber-lp-tokens job for OPOS hackaton ez

### CODE REVIEW

**Comment by olivbau** [comment]
Some notes:
* You can use cache.getTokenPrices instead of runInBatch
* I switched mints into a set to avoid having multiple times same mint into the array
* I add type to the Axios SABER_SWAPS request (thanks to https://app.quicktype.io/)
* I verify that lpMint supply is not zero to avoid dividing by 0

I'll fully test the job later today and then merge

**Comment by UbermenschSYM** [comment]
Maybe modify runInBatch to cache.getTokenPrices in other jobs as well?(raydium-lp-tokens for example). Or is there any reason why cache.getTokenPrices is better in this case?
Great feedback, thanks!

**Comment by olivbau** [comment]
at th

> Maybe modify runInBatch to cache.getTokenPrices in other jobs as well?(raydium-lp-tokens for example). Or is there any reason why cache.getTokenPrices is better in this case? Great feedback, thanks!

at that time getTokenPrices was not dev yet. but yes, we'll have to migrate

**Comment by olivbau** [comment]
BTW price was not correct
https://github.com/sonarwatch/portfolio/pull/1/commits/f7bf2ac1fa4ccc90d72510b6d4b062c8991e7b72

**Comment by UbermenschSYM** [comment]
True. mb

**Pull request merged**
